--SELECT to_char(DBMS_METADATA.GET_DDL ('CONSTRAINT', 'VEHBODYTYPETEXT', 'DIGIMASTER')) from dual;

--spool "Constraint DIGITAL_CONFIG.CV_CSG_FK.sql"
SELECT TO_CHAR(DBMS_METADATA.GET_DDL ('CONSTRAINT', 'CV_CSG_FK','DIGITAL_CONFIG')) FROM DUAL;
--spool off


select * from all_CONSTRAINTS WHERE CONSTRAINT_NAME='CV_CSG_FK'
